# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI & CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 📂 Sync files    
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: sftp
        remote-host: pi.caojiantao.site
        remote-port: 2048
        remote-user: root
        remote-password: ${{ secrets.PASSWORD }}
        sync: full
        local-path: ./
        remote-path: /var/www/live
